name: package_test

on:
  workflow_dispatch:
  push:
    branches:
      - dev

jobs:
  cache_and_install:
    runs-on: ubuntu-latest
    env:
      PATH: ${{ runner.toolsDirectory }}/flutter/bin:$PATH
    steps:
      - uses: actions/checkout@v3

      - name: Cache Flutter
        id: cache_flutter
        uses: actions/cache@v2
        with:
          path: ~/.pub-cache
          key: ${{ runner.os }}-flutter-cache-${{ hashFiles('.flutter-version') }}

      - name: Setup Flutter
        run: |
          mkdir -p $HOME/bin
          curl -fsSL https://raw.githubusercontent.com/USERNAME/REPOSITORY/BRANCH/setup.sh -o $HOME/bin/setup_flutter.sh
          chmod +x $HOME/bin/setup_flutter.sh
          $HOME/bin/setup_flutter.sh -n latest
          echo "::add-path::$HOME/.flutter-sdk/bin" # Add Flutter to PATH

      - name: Cache Java
        id: cache_java
        uses: actions/cache@v2
        with:
          path: ~/Library/Android/sdk
          key: ${{ runner.os }}-java-cache-${{ hashFiles('build.gradle') }}

      - name: Install Java (if not cached)
        if: steps.cache_java.outputs.cache-hit != 'true'
        run: |
          # Install Java if cache was not found
          # Use your Java installation commands here

  test:
    runs-on: ubuntu-latest
    needs: cache_and_install
    steps:
      - uses: actions/checkout@v2
      - name: Set up Flutter
        run: |
          flutter pub get
          flutter analyze .
