name: Version, Analyze, and Publish

on:
  workflow_dispatch:
  push:
    branches:
      - dev

jobs:
  bump_version_analyze_publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Cache Flutter Dependencies
        uses: actions/cache@v2
        with:
          path: ~/.pub-cache
          key: ${{ runner.os }}-flutter-${{ hashFiles('**/pubspec.yaml') }}

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.12.2" # Set the Flutter version you want to use

      - name: Get Previous Tag
        id: get_previous_tag
        run: echo ::set-output name=PREV_TAG::$(git describe --abbrev=0 --tags)

      - name: Get Current Version
        id: get_current_version
        run: echo ::set-output name=CURR_VERSION::$(flutter --version | grep -o "Flutter [0-9.]*" | cut -d " " -f 2)

      - name: Increment Version
        id: increment_version
        run: echo ::set-output name=NEW_VERSION::$(bash -c "echo \${${{ steps.get_current_version.outputs.CURR_VERSION }}%.*}.$((${{ steps.get_current_version.outputs.CURR_VERSION }} | awk -F '.' '{print $NF}') + 1)")

      - name: Update pubspec.yaml
        run: sed -i "s/version: ${GITHUB_REF#refs/tags\//}/version: ${{ steps.increment_version.outputs.NEW_VERSION }}/" pubspec.yaml

      - name: Analyze Package
        run: flutter analyze

      - name: Publish Package
        run: |
          flutter pub publish
