name: package_test

on:
  workflow_dispatch:
  push:
    branches:
      - dev

jobs:
  # Cache Flutter dependencies
  cache_flutter:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Cache Flutter Dependencies
        uses: actions/cache@v2
        with:
          path: ~/.pub-cache
          key: ${{ runner.os }}-flutter-${{ hashFiles('**/pubspec.yaml') }}

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.13.2"

      - name: Test Package
        run: flutter pub get && flutter analyze .

  # Subsequent job using cached dependencies
  test:
    needs: cache_flutter
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.13.2"

      - name: Use Cached Flutter Dependencies
        uses: actions/cache@v2
        with:
          path: ~/.pub-cache
          key: ${{ runner.os }}-flutter-${{ hashFiles('**/pubspec.yaml') }}

      - name: Test Package
        run: flutter pub get && flutter analyze .
