name: dev

on:
  workflow_dispatch:

  push:
    branches:
      - "dev"

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup Path
        run: |
          echo "/usr/lib/dart/bin" >> $GITHUB_PATH
          echo "$HOME/.pub-cache/bin" >> $GITHUB_PATH

      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
             flutter-version: '3.13.2'

      - name: Install project dependencies
        run:  flutter pub get

      - name: Run code generation
        run:  flutter pub run build_runner build --delete-conflicting-outputs

      - name: Run static analysis
        run:  flutter analyze .

      - name: Run tests
        run:  flutter test --no-pub --test-randomize-ordering-seed random