name: package_test

on:
  workflow_dispatch:

  push:
    branches:
      - dev

jobs:
  # Test Package
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      # Use cache with restore keys and custom refresh command
      - uses: actions/cache@v3
        with:
          path: ~/.pub-cache
          key: ${{ runner.os }}-pub-cache-${{ hashFiles('pubspec.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pub-cache-
          # Clear cache after 3 jobs
          refresh-command: |
            if [[ $(jobs -r | wc -l) -eq 3 ]]; then rm -rf ~/.pub-cache; fi
            flutter pub get
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.13.2"
      - run: flutter pub get
      - run: flutter analyze .

  # Bump Version
  bump_version:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "16"
      # Use the same cache with restore keys and refresh command
      - uses: actions/cache@v3
        with:
          path: ~/.pub-cache
          key: ${{ runner.os }}-pub-cache-${{ hashFiles('pubspec.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pub-cache-
          refresh-command: |
            if [[ $(jobs -r | wc -l) -eq 3 ]]; then rm -rf ~/.pub-cache; fi
            flutter pub get
      - run: flutter pub get
      - run: npm version patch # Increment patch version
      - run: git add pubspec.yaml && git commit -m "Bump version to [version]"

  # Publish Package
  publish_package:
    runs-on: ubuntu-latest
    needs: bump_version
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "16"
      # Use the same cache with restore keys and refresh command
      - uses: actions/cache@v3
        with:
          path: ~/.pub-cache
          key: ${{ runner.os }}-pub-cache-${{ hashFiles('pubspec.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pub-cache-
          refresh-command: |
            if [[ $(jobs -r | wc -l) -eq 3 ]]; then rm -rf ~/.pub-cache; fi
            flutter pub get
      - run: flutter pub get
      - run: dart run build_runner build
      - uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUBTOKEN}}
          file: build/outputs/package/rq_network-0.0.1.tar.gz
          tag: v[version]
          prerelease: false
          overwrite: true
