name: package_test

on:
  workflow_dispatch:
  push:
    branches:
      - dev

jobs:
  cache_and_install:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Cache Flutter
        id: cache_flutter
        uses: actions/cache@v2
        with:
          path: ~/.pub-cache
          key: ${{ runner.os }}-flutter-cache-${{ hashFiles('.flutter-version') }}

      - name: Install Flutter
        if: steps.cache_flutter.outputs.cache-hit != 'true'
        run: |
          git clone https://github.com/flutter/flutter.git -b stable
          export PATH="$PATH:`pwd`/flutter/bin"
          flutter precache
          flutter doctor -v  # Verify Flutter installation

      - name: Cache Java
        id: cache_java
        uses: actions/cache@v2
        with:
          path: ~/Library/Android/sdk
          key: ${{ runner.os }}-java-cache-${{ hashFiles('build.gradle') }}

      - name: Install Java (if not cached)
        if: steps.cache_java.outputs.cache-hit != 'true'
        run: |
          # Install Java if cache was not found
          # Use your Java installation commands here

  test:
    runs-on: ubuntu-latest
    needs: cache_and_install
    steps:
      - uses: actions/checkout@v2
      - run: flutter pub get
      - run: flutter analyze .

  bump_version:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "16"
      - run: flutter pub get
      - name: Get current version
        run: |
          current_version=$(cat pubspec.yaml | grep version | sed 's/version: //')
          echo "Current version: $current_version"
      - name: Increment version
        run: |
          new_version=$(echo "$current_version" | awk -F. '{printf "%d.%d.%d\n", $1,$2,$3+1}')
          echo "New version: $new_version"
      - name: Update pubspec.yaml
        run: |
          sed -i "s/version: $current_version/version: $new_version/" pubspec.yaml
      - run: git add pubspec.yaml && git commit -m "Bump version to $new_version"
      - name: Create tag (optional)
        run: git tag "v$new_version"

  publish_package:
    runs-on: ubuntu-latest
    needs: bump_version
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "16"
      - run: flutter pub get
      - run: dart run build_runner build
      # Fetch npm version here using appropriate commands
      - name: Set npm_version
        id: set_npm_version
        run: echo "::set-output name=npm_version::1.0.0" # Replace with actual npm version retrieval command
      - name: Update file name
        run: |
          mv build/outputs/package/my_package-0.0.1.tar.gz "build/outputs/package/rq_network-${{ steps.set_npm_version.outputs.npm_version }}.tar.gz"
      - uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUBTOKEN }}
          file: "build/outputs/package/rq_network-${{ steps.set_npm_version.outputs.npm_version }}.tar.gz"
          tag: v${{ needs.bump
