name: package_test

on:
  workflow_dispatch:

  push:
    branches:
      - dev

jobs:
  # Test Package
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.13.2"
      - run: flutter pub get
      - run: flutter analyze .
      - uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{secrets.GITHUB_TOKEN }}
          file: build/outputs/package/rq_network-0.0.1.tar.gz
          tag: v[version]
          prerelease: false
          overwrite: true
